### ISSUE TITLE
Error: Cannot find module 'module-alias' - Running the Example Function 

### ISSUE THREAD

**Issue by pip8786** [productbrew/gcf-monorepo#1]
I tried following the readme by doing `yarn install` and then `yarn workspace @productbrew/funny-world dev` and got the following error, which is very similar to what I've been getting trying to create a similar setup (typescript cloud functions dependent on local typescript packages):

```
Provided module can't be loaded.
Did you list all required modules in the package.json dependencies?
Detailed stack trace: Error: Cannot find module 'module-alias'
Require stack:
 - /Users/phsabo/Downloads/gcf-monorepo-main/functions/funny-world/dist/index.js
 - /Users/phsabo/Downloads/gcf-monorepo-main/node_modules/@google-cloud/functions-framework/build/src/loader.js
 - /Users/phsabo/Downloads/gcf-monorepo-main/node_modules/@google-cloud/functions-framework/build/src/main.js
     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
     at Module.require (node:internal/modules/cjs/loader:1005:19)
     at require (node:internal/modules/cjs/helpers:102:18)
     at Object.<anonymous> (/Users/phsabo/Downloads/gcf-monorepo-main/functions/funny-world/dist/index.js:2:21)
     at Module._compile (node:internal/modules/cjs/loader:1105:14)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     at Module.require (node:internal/modules/cjs/loader:1005:19)
 Could not load the function, shutting down.
```
Using yarn version `1.22.19`, node version `v.16.16.0` and npm `8.11.0`.  

Does this example repository still work for you if you install it fresh?

Thanks for creating this example monorepo.

**Comment by czystyl** [comment]
Hello @pip8786! 
The repository was not updated after we did a few fixes.

Give me a few days, and I'll try to update the repository with the updated CLI version. 

To resolve your error quickly, add the [module-alias](https://www.npmjs.com/package/module-alias) package to the function. The updated CLI does it automatically.

**Comment by czystyl** [comment]
@pip8786 You can take a look at the changes here: https://github.com/productbrew/gcf-monorepo/pull/2

Let me know if you spot any other issues.

**Comment by pip8786** [comment]
@czystyl Maybe I'm missing something, I cloned the repository fresh, did `yarn install` then `yarn workspace @productbrew/funny-world dev` as stated in your readme, and still get: `Function package.json does not include "module-alias" package.`. I've tried adding `module-alias` to the `funny-world` `package.json` dependencies, but that doesn't resolve the issue. Are your example functions not meant to work out of the box? I'm just following your readme to make sure it works before I try to adopt it for my repository.

Thanks!

**Comment by czystyl** [comment]
Sorry I didn't remove one check. 

I added as well support for .env so you can check this commit: https://github.com/productbrew/gcf-monorepo/commit/b341c8715f18a31a3c84f1fb73e2247c52645ecf

**Comment by pip8786** [comment]
Thanks, that latest commit makes it work using your readme. 

My setup is a bit different with NPM workspaces (only way I could get Prisma to work) and my modules are ESNext instead of commonjs, but I might try converting and see if it still works. The problem is I also have NextJS depending on the same internal packages so getting everything to work together in a single monorepo is proving tricky. 

I'll be using your repository as a reference though to try and get it working!

**Comment by czystyl** [comment]
Great to head that! 

Let me know if you'll need any help 🙌
